// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbvhuhakkftzxhbxtras.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidmh1aGFra2Z0enhoYnh0cmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTU3MTEsImV4cCI6MjA1NzY5MTcxMX0.vzy-Cok81uyQbdaPnfrU0gXv1FR1szwpXvoumDU0Of8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);